name: Rupee_Rush
description: "GLF Demo ."
publish_to: 'none'
version: 2.0.1+3  # 主版本.次版本.修订号+构建号

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0 #国际化插件
  cupertino_icons: ^1.0.8 #flutter自带的图标库
  get: ^4.7.2 #状态管理 路由管理
  flutter_screenutil: ^5.9.3 #布局适配
  dio: ^5.8.0+1 #网络请求
  encrypt_shared_preferences: ^0.9.9 #本地存储加密
  flutter_easyloading: ^3.0.5 # 加载/提示错误弹窗
  flutter_inappwebview: ^6.1.5 # webview
  encrypt: ^5.0.3 #加密
  crypto: ^3.0.6 #加密
  pointycastle: ^3.9.1 #加密
  share_plus: ^11.0.0 #分享
  card_swiper: ^3.0.1 #轮播图
  animated_splash_screen: ^1.3.0 #启动页
  lottie: ^3.3.1 #动画
  delightful_toast: ^1.1.0 #toast



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_gen_runner: ^5.10.0 #dart run build_runner build
  build_runner: ^2.4.15

flutter_intl:
  enabled: true

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/public/
    - assets/start/


  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #


